import type { Dataset, Organization, Theme, User, UseCase, Comment, Review, Activity, Stats, DatasetStats } from '@/types';

// Themes
export const themes: Theme[] = [
  {
    id: 'theme-1',
    slug: 'economie',
    name: 'Économie',
    description: 'Données économiques, finances, commerce, investissements',
    icon: 'TrendingUp',
    color: '#2563eb',
    datasetsCount: 12,
  },
  {
    id: 'theme-2',
    slug: 'sante',
    name: 'Santé',
    description: 'Établissements de santé, épidémiologie, statistiques sanitaires',
    icon: 'Heart',
    color: '#dc2626',
    datasetsCount: 8,
  },
  {
    id: 'theme-3',
    slug: 'education',
    name: 'Éducation',
    description: 'Établissements scolaires, effectifs, résultats exams',
    icon: 'GraduationCap',
    color: '#7c3aed',
    datasetsCount: 10,
  },
  {
    id: 'theme-4',
    slug: 'environnement',
    name: 'Environnement',
    description: 'Climat, biodiversité, ressources naturelles, pollution',
    icon: 'Leaf',
    color: '#16a34a',
    datasetsCount: 6,
  },
  {
    id: 'theme-5',
    slug: 'transport',
    name: 'Transport',
    description: 'Infrastructures routières, trafic, transports publics',
    icon: 'Truck',
    color: '#f59e0b',
    datasetsCount: 5,
  },
  {
    id: 'theme-6',
    slug: 'agriculture',
    name: 'Agriculture',
    description: 'Production agricole, élevage, pêche, forêts',
    icon: 'Wheat',
    color: '#78350f',
    datasetsCount: 8,
  },
  {
    id: 'theme-7',
    slug: 'demographie',
    name: 'Démographie',
    description: 'Population, migrations, recensement, ménages',
    icon: 'Users',
    color: '#0891b2',
    datasetsCount: 5,
  },
  {
    id: 'theme-8',
    slug: 'finances',
    name: 'Finances Publiques',
    description: 'Budget, fiscalité, dépenses publiques, dette',
    icon: 'DollarSign',
    color: '#eab308',
    datasetsCount: 7,
  },
];

// Organizations
export const organizations: Organization[] = [
  {
    id: 'org-1',
    name: 'Ministère de l\'Économie et des Finances',
    type: 'ministry',
    logo: '/logos/mef.png',
    description: 'Ministère chargé de la politique économique et financière du Mali',
    email: 'contact@mef.gov.ml',
    phone: '+223 20 21 32 00',
    website: 'https://mef.gov.ml',
    datasetsCount: 15,
    totalDownloads: 45230,
    createdAt: new Date('2020-01-15'),
    status: 'active',
  },
  {
    id: 'org-2',
    name: 'Ministère de la Santé et de l\'Hygiène Publique',
    type: 'ministry',
    logo: '/logos/msp.png',
    description: 'Ministère en charge de la politique sanitaire nationale',
    email: 'contact@sante.gov.ml',
    phone: '+223 20 22 45 67',
    website: 'https://sante.gov.ml',
    datasetsCount: 12,
    totalDownloads: 38920,
    createdAt: new Date('2020-03-01'),
    status: 'active',
  },
  {
    id: 'org-3',
    name: 'Ministère de l\'Éducation Nationale',
    type: 'ministry',
    logo: '/logos/men.png',
    description: 'Ministère responsable du système éducatif malien',
    email: 'contact@education.gov.ml',
    phone: '+223 20 21 45 78',
    website: 'https://education.gov.ml',
    datasetsCount: 18,
    totalDownloads: 52100,
    createdAt: new Date('2020-02-10'),
    status: 'active',
  },
  {
    id: 'org-4',
    name: 'Institut National de la Statistique (INSTAT)',
    type: 'institute',
    logo: '/logos/instat.png',
    description: 'Organisme officiel de statistiques du Mali',
    email: 'info@instat.ml',
    phone: '+223 20 21 90 12',
    website: 'https://instat.ml',
    datasetsCount: 25,
    totalDownloads: 67890,
    createdAt: new Date('2019-06-01'),
    status: 'active',
  },
  {
    id: 'org-5',
    name: 'Direction Nationale de l\'Agriculture',
    type: 'agency',
    logo: '/logos/dna.png',
    description: 'Direction technique du Ministère de l\'Agriculture',
    email: 'contact@agriculture.gov.ml',
    phone: '+223 20 22 12 34',
    website: 'https://agriculture.gov.ml',
    datasetsCount: 10,
    totalDownloads: 23450,
    createdAt: new Date('2020-04-15'),
    status: 'active',
  },
  {
    id: 'org-6',
    name: 'Ministère de l\'Environnement et de l\'Assainissement',
    type: 'ministry',
    logo: '/logos/mea.png',
    description: 'Ministère chargé de la protection de l\'environnement',
    email: 'contact@environnement.gov.ml',
    phone: '+223 20 23 56 78',
    website: 'https://environnement.gov.ml',
    datasetsCount: 8,
    totalDownloads: 18900,
    createdAt: new Date('2020-05-20'),
    status: 'active',
  },
  {
    id: 'org-7',
    name: 'Direction Nationale des Infrastructures Routières',
    type: 'agency',
    logo: '/logos/dnir.png',
    description: 'Gestion du réseau routier national',
    email: 'contact@dnir.gov.ml',
    phone: '+223 20 22 89 01',
    website: 'https://dnir.gov.ml',
    datasetsCount: 6,
    totalDownloads: 15670,
    createdAt: new Date('2020-07-10'),
    status: 'active',
  },
  {
    id: 'org-8',
    name: 'Ministère des Affaires Étrangères',
    type: 'ministry',
    logo: '/logos/mae.png',
    description: 'Diplomatie et relations internationales',
    email: 'contact@mfa.gov.ml',
    phone: '+223 20 22 33 44',
    website: 'https://mfa.gov.ml',
    datasetsCount: 5,
    totalDownloads: 12340,
    createdAt: new Date('2020-08-05'),
    status: 'active',
  },
  {
    id: 'org-9',
    name: 'Mairie de Bamako',
    type: 'municipality',
    logo: '/logos/bamako.png',
    description: 'Commune du District de Bamako',
    email: 'contact@bamako.ml',
    phone: '+223 20 22 55 66',
    website: 'https://bamako.ml',
    datasetsCount: 7,
    totalDownloads: 21000,
    createdAt: new Date('2020-09-12'),
    status: 'active',
  },
  {
    id: 'org-10',
    name: 'Observatoire du Développement Durable',
    type: 'institute',
    logo: '/logos/odd.png',
    description: 'Suivi et évaluation des objectifs de développement durable',
    email: 'info@odd.ml',
    phone: '+223 20 21 67 89',
    website: 'https://odd.ml',
    datasetsCount: 9,
    totalDownloads: 17890,
    createdAt: new Date('2020-10-01'),
    status: 'active',
  },
  {
    id: 'org-11',
    name: 'Direction Générale des Impôts',
    type: 'agency',
    logo: '/logos/dgi.png',
    description: 'Administration fiscale nationale',
    email: 'contact@impots.gov.ml',
    phone: '+223 20 22 77 88',
    website: 'https://impots.gov.ml',
    datasetsCount: 6,
    totalDownloads: 14560,
    createdAt: new Date('2020-11-15'),
    status: 'active',
  },
  {
    id: 'org-12',
    name: 'Autorité de Régulation des Télécommunications',
    type: 'agency',
    logo: '/logos/artp.png',
    description: 'Régulation du secteur des télécommunications',
    email: 'contact@artp.ml',
    phone: '+223 20 22 99 00',
    website: 'https://artp.ml',
    datasetsCount: 5,
    totalDownloads: 13200,
    createdAt: new Date('2020-12-20'),
    status: 'active',
  },
  {
    id: 'org-13',
    name: 'Banque Centrale des États de l\'Afrique de l\'Ouest',
    type: 'institute',
    logo: '/logos/bceao.png',
    description: 'Institut d\'émission de l\'UEMOA',
    email: 'contact@bceao.int',
    phone: '+223 20 23 11 22',
    website: 'https://bceao.int',
    datasetsCount: 8,
    totalDownloads: 28760,
    createdAt: new Date('2019-12-01'),
    status: 'active',
  },
  {
    id: 'org-14',
    name: 'Ministère de l\'Énergie et de l\'Eau',
    type: 'ministry',
    logo: '/logos/mee.png',
    description: 'Politique énergétique nationale',
    email: 'contact@energie.gov.ml',
    phone: '+223 20 22 44 55',
    website: 'https://energie.gov.ml',
    datasetsCount: 7,
    totalDownloads: 16890,
    createdAt: new Date('2021-01-10'),
    status: 'active',
  },
  {
    id: 'org-15',
    name: 'Commission Électorale Nationale Indépendante',
    type: 'agency',
    logo: '/logos/ceni.png',
    description: 'Organisation et supervision des élections',
    email: 'contact@ceni.ml',
    phone: '+223 20 21 00 11',
    website: 'https://ceni.ml',
    datasetsCount: 4,
    totalDownloads: 11200,
    createdAt: new Date('2021-02-15'),
    status: 'active',
  },
];

// Datasets
export const datasets: Dataset[] = [
  {
    id: 'ds-1',
    title: 'Établissements scolaires du Mali (2024)',
    description: 'Recensement complet de tous les établissements d\'enseignement primaire, secondaire et supérieur sur le territoire national. Données incluent les coordonnées géographiques, les effectifs, les infrastructures et les équipements disponibles.',
    organization: organizations[2],
    theme: themes[2],
    keywords: ['éducation', 'écoles', 'établissements', 'enseignement', 'primaire', 'secondaire', 'supérieur'],
    formats: ['CSV', 'GeoJSON', 'Excel'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
    updateFrequency: 'Annuel',
    downloads: 12543,
    views: 45230,
    rating: 4.5,
    ratingCount: 87,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-1',
        name: 'etablissements_scolaires_2024.csv',
        format: 'CSV',
        size: 2450000,
        url: '/data/ds-1/etablissements_scolaires_2024.csv',
        checksum: 'abc123def456',
        rows: 15432,
        columns: 24,
        addedAt: new Date('2024-01-15'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Éducation Nationale',
      contactEmail: 'contact@education.gov.ml',
      granularity: 'Établissement',
    },
    quality: {
      overall: 92,
      completeness: 95,
      accuracy: 90,
      documentation: 90,
      metadata: 95,
      formats: 90,
      updates: 90,
    },
    status: 'published',
    featured: true,
  },
  {
    id: 'ds-2',
    title: 'Centres de santé et hôpitaux par région',
    description: 'Inventaire national des structures sanitaires publiques et privées. Le jeu de données comprend les centres de santé communautaires, les centres de santé de référence, les hôpitaux régionaux et nationaux avec leurs capacités d\'accueil et équipements.',
    organization: organizations[1],
    theme: themes[1],
    keywords: ['santé', 'hôpitaux', 'centres de santé', 'infrastructure sanitaire', 'région'],
    formats: ['CSV', 'GeoJSON', 'PDF'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-05-15'),
    updateFrequency: 'Annuel',
    downloads: 8756,
    views: 32100,
    rating: 4.3,
    ratingCount: 62,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-2',
        name: 'centres_sante_mali_2024.csv',
        format: 'CSV',
        size: 1850000,
        url: '/data/ds-2/centres_sante_mali_2024.csv',
        checksum: 'def789ghi012',
        rows: 8542,
        columns: 18,
        addedAt: new Date('2024-02-20'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de la Santé et de l\'Hygiène Publique',
      contactEmail: 'contact@sante.gov.ml',
      granularity: 'Établissement',
    },
    quality: {
      overall: 88,
      completeness: 90,
      accuracy: 85,
      documentation: 88,
      metadata: 92,
      formats: 85,
      updates: 88,
    },
    status: 'published',
    featured: true,
  },
  {
    id: 'ds-3',
    title: 'Production agricole annuelle par culture (2018-2024)',
    description: 'Statistiques de la production agricole annuelle par type de culture (céréales, oléagineux, légumineuses, cultures de rente). Données ventilées par région et par campagne agricole.',
    organization: organizations[4],
    theme: themes[5],
    keywords: ['agriculture', 'production', 'céréales', 'cultures', 'campagne agricole', 'région'],
    formats: ['CSV', 'Excel'],
    license: 'CC-BY-SA-4.0',
    publishedAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
    updateFrequency: 'Annuel',
    downloads: 6789,
    views: 24560,
    rating: 4.2,
    ratingCount: 48,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2018-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-3',
        name: 'production_agricole_2018_2024.csv',
        format: 'CSV',
        size: 1250000,
        url: '/data/ds-3/production_agricole_2018_2024.csv',
        checksum: 'ghi345jkl678',
        rows: 2145,
        columns: 12,
        addedAt: new Date('2024-03-10'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Direction Nationale de l\'Agriculture',
      contactEmail: 'contact@agriculture.gov.ml',
      granularity: 'Région',
    },
    quality: {
      overall: 85,
      completeness: 88,
      accuracy: 82,
      documentation: 85,
      metadata: 88,
      formats: 85,
      updates: 85,
    },
    status: 'published',
    featured: true,
  },
  {
    id: 'ds-4',
    title: 'Indicateurs économiques trimestriels (2020-2024)',
    description: 'Principaux indicateurs économiques du Mali : PIB, inflation, balance commerciale, taux de change, investissements, épargne. Données trimestrielles avec comparaisons interannuelles.',
    organization: organizations[3],
    theme: themes[0],
    keywords: ['économie', 'PIB', 'inflation', 'balance commerciale', 'taux de change', 'trimestriel'],
    formats: ['CSV', 'Excel', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-07-01'),
    updateFrequency: 'Trimestriel',
    downloads: 9234,
    views: 38700,
    rating: 4.6,
    ratingCount: 102,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-06-30') },
    files: [
      {
        id: 'file-4',
        name: 'indicateurs_economiques_trimestriels.csv',
        format: 'CSV',
        size: 890000,
        url: '/data/ds-4/indicateurs_economiques_trimestriels.csv',
        checksum: 'jkl901mno234',
        rows: 540,
        columns: 15,
        addedAt: new Date('2024-04-15'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Institut National de la Statistique',
      contactEmail: 'info@instat.ml',
      granularity: 'Trimestriel',
    },
    quality: {
      overall: 95,
      completeness: 95,
      accuracy: 95,
      documentation: 92,
      metadata: 98,
      formats: 95,
      updates: 95,
    },
    status: 'published',
    featured: true,
  },
  {
    id: 'ds-5',
    title: 'Réseau routier national - État et caractéristiques',
    description: 'Inventaire complet du réseau routier national avec classification (bitumée, latéritique, piste), état général, longueurs, et coordonnées des tronçons.',
    organization: organizations[6],
    theme: themes[4],
    keywords: ['transport', 'routes', 'infrastructures', 'réseau routier', 'tronçons', 'bitumée'],
    formats: ['GeoJSON', 'Shapefile', 'CSV'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    updateFrequency: 'Annuel',
    downloads: 5432,
    views: 21500,
    rating: 4.4,
    ratingCount: 56,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-5',
        name: 'reseau_routier_national_2024.geojson',
        format: 'GeoJSON',
        size: 15600000,
        url: '/data/ds-5/reseau_routier_national_2024.geojson',
        checksum: 'mno567pqr890',
        rows: 15432,
        columns: 12,
        addedAt: new Date('2024-01-25'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Direction Nationale des Infrastructures Routières',
      contactEmail: 'contact@dnir.gov.ml',
      granularity: 'Tronçon',
    },
    quality: {
      overall: 90,
      completeness: 92,
      accuracy: 88,
      documentation: 90,
      metadata: 92,
      formats: 88,
      updates: 90,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-6',
    title: 'Recensement Général de la Population et de l\'Habitat (RGPH) 2024',
    description: 'Données officielles du dernier recensement de la population malienne : effectifs par région, cercle, commune, structure par âge et sexe, ménages, taux d\'urbanisation.',
    organization: organizations[3],
    theme: themes[6],
    keywords: ['démographie', 'population', 'recensement', 'RGPH', 'ménages', 'urbanisation'],
    formats: ['CSV', 'Excel', 'PDF', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
    updateFrequency: 'Biennal',
    downloads: 23456,
    views: 89700,
    rating: 4.8,
    ratingCount: 234,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-6',
        name: 'rgph_2024_effectifs.csv',
        format: 'CSV',
        size: 3450000,
        url: '/data/ds-6/rgph_2024_effectifs.csv',
        checksum: 'pqr345stu678',
        rows: 19876,
        columns: 18,
        addedAt: new Date('2024-06-01'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Institut National de la Statistique',
      contactEmail: 'info@instat.ml',
      granularity: 'Commune',
    },
    quality: {
      overall: 98,
      completeness: 98,
      accuracy: 98,
      documentation: 98,
      metadata: 98,
      formats: 98,
      updates: 98,
    },
    status: 'published',
    featured: true,
  },
  {
    id: 'ds-7',
    title: 'Statistiques du commerce extérieur (2020-2024)',
    description: 'Données détaillées des importations et exportations du Mali par produit et partenaire commercial. Valeurs FOB, volumes et balance commerciale mensuelle.',
    organization: organizations[0],
    theme: themes[0],
    keywords: ['commerce', 'exportations', 'importations', 'balance commerciale', 'partenaires', 'produits'],
    formats: ['CSV', 'Excel', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-07-15'),
    updateFrequency: 'Mensuel',
    downloads: 7890,
    views: 32450,
    rating: 4.5,
    ratingCount: 89,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-06-30') },
    files: [
      {
        id: 'file-7',
        name: 'commerce_exterieur_2020_2024.csv',
        format: 'CSV',
        size: 2340000,
        url: '/data/ds-7/commerce_exterieur_2020_2024.csv',
        checksum: 'stu789vwx012',
        rows: 12450,
        columns: 16,
        addedAt: new Date('2024-05-20'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Économie et des Finances',
      contactEmail: 'contact@mef.gov.ml',
      granularity: 'Produit',
    },
    quality: {
      overall: 92,
      completeness: 90,
      accuracy: 92,
      documentation: 90,
      metadata: 95,
      formats: 92,
      updates: 92,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-8',
    title: 'Données météorologiques Bamako (2015-2024)',
    description: 'Séries temporelles des données météorologiques de Bamako : température, précipitations, humidité, vitesse du vent, pression atmosphérique. Données journalières de la station principale.',
    organization: organizations[5],
    theme: themes[3],
    keywords: ['météo', 'climat', 'température', 'précipitations', 'Bamako', 'station météo'],
    formats: ['CSV', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-06-30'),
    updateFrequency: 'Mensuel',
    downloads: 4321,
    views: 18900,
    rating: 4.1,
    ratingCount: 45,
    spatialCoverage: 'Bamako',
    temporalCoverage: { start: new Date('2015-01-01'), end: new Date('2024-06-30') },
    files: [
      {
        id: 'file-8',
        name: 'meteo_bamako_2015_2024.csv',
        format: 'CSV',
        size: 12500000,
        url: '/data/ds-8/meteo_bamako_2015_2024.csv',
        checksum: 'vwx234yza567',
        rows: 3456,
        columns: 8,
        addedAt: new Date('2024-02-28'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Environnement et de l\'Assainissement',
      contactEmail: 'contact@environnement.gov.ml',
      granularity: 'Journalier',
    },
    quality: {
      overall: 88,
      completeness: 90,
      accuracy: 85,
      documentation: 85,
      metadata: 90,
      formats: 90,
      updates: 88,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-9',
    title: 'Budget National de l\'État - Loi de Finances 2024',
    description: 'Budget voté pour l\'exercice 2024 : recettes et dépenses par ministère, type de dépenses (fonctionnement, investissement, dette), et chapitres budgétaires.',
    organization: organizations[0],
    theme: themes[7],
    keywords: ['budget', 'finances', 'loi de finances', 'dépenses', 'recettes', 'ministères'],
    formats: ['CSV', 'Excel', 'PDF'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    updateFrequency: 'Annuel',
    downloads: 15678,
    views: 67890,
    rating: 4.7,
    ratingCount: 167,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-9',
        name: 'budget_etat_2024.csv',
        format: 'CSV',
        size: 1890000,
        url: '/data/ds-9/budget_etat_2024.csv',
        checksum: 'yza678bcd901',
        rows: 2890,
        columns: 14,
        addedAt: new Date('2024-01-01'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Économie et des Finances',
      contactEmail: 'contact@mef.gov.ml',
      granularity: 'Ministère',
    },
    quality: {
      overall: 95,
      completeness: 98,
      accuracy: 95,
      documentation: 95,
      metadata: 95,
      formats: 92,
      updates: 95,
    },
    status: 'published',
    featured: true,
  },
  {
    id: 'ds-10',
    title: 'Effectifs enseignants par niveau et région (2024)',
    description: 'Statistiques des enseignants du Mali par niveau d\'enseignement (primaire, secondaire, supérieur), par région et par discipline. Données sur le personnel titulaire et contractuel.',
    organization: organizations[2],
    theme: themes[2],
    keywords: ['éducation', 'enseignants', 'effectifs', 'personnel', 'primaire', 'secondaire', 'supérieur'],
    formats: ['CSV', 'Excel'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-25'),
    updateFrequency: 'Annuel',
    downloads: 5678,
    views: 23400,
    rating: 4.3,
    ratingCount: 52,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-10',
        name: 'effectifs_enseignants_2024.csv',
        format: 'CSV',
        size: 1450000,
        url: '/data/ds-10/effectifs_enseignants_2024.csv',
        checksum: 'bcd901def234',
        rows: 15678,
        columns: 12,
        addedAt: new Date('2024-03-25'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Éducation Nationale',
      contactEmail: 'contact@education.gov.ml',
      granularity: 'Région',
    },
    quality: {
      overall: 88,
      completeness: 90,
      accuracy: 85,
      documentation: 88,
      metadata: 90,
      formats: 88,
      updates: 88,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-11',
    title: 'Épidémiologie du Paludisme - Cas déclarés par région (2020-2024)',
    description: 'Surveillance épidémiologique du paludisme au Mali : nombre de cas déclarés, décès, incidence par région. Données mensuelles ventilées par tranche d\'âge.',
    organization: organizations[1],
    theme: themes[1],
    keywords: ['santé', 'paludisme', 'épidémiologie', 'cas', 'décès', 'incidence', 'région'],
    formats: ['CSV', 'Excel', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-30'),
    updateFrequency: 'Mensuel',
    downloads: 4567,
    views: 19800,
    rating: 4.4,
    ratingCount: 61,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-06-30') },
    files: [
      {
        id: 'file-11',
        name: 'paludisme_cases_2020_2024.csv',
        format: 'CSV',
        size: 890000,
        url: '/data/ds-11/paludisme_cases_2020_2024.csv',
        checksum: 'def234efg345',
        rows: 8640,
        columns: 10,
        addedAt: new Date('2024-04-10'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de la Santé et de l\'Hygiène Publique',
      contactEmail: 'contact@sante.gov.ml',
      granularity: 'Région',
    },
    quality: {
      overall: 90,
      completeness: 88,
      accuracy: 92,
      documentation: 90,
      metadata: 92,
      formats: 90,
      updates: 88,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-12',
    title: 'Parcs éoliens et solaires - Capacités installées par région',
    description: 'Inventaire des installations d\'énergie renouvelable au Mali : parcs éoliens, centrales solaires photovoltaïques et thermiques. Capacités installées, production annuelle et projets en cours.',
    organization: organizations[13],
    theme: themes[3],
    keywords: ['énergie', 'renouvelable', 'solaire', 'éolien', 'électricité', 'capacité', 'région'],
    formats: ['CSV', 'GeoJSON', 'PDF'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-20'),
    updateFrequency: 'Semestriel',
    downloads: 3456,
    views: 15400,
    rating: 4.2,
    ratingCount: 38,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-12',
        name: 'energie_renouvelable_2024.csv',
        format: 'CSV',
        size: 670000,
        url: '/data/ds-12/energie_renouvelable_2024.csv',
        checksum: 'efg456fgh567',
        rows: 234,
        columns: 14,
        addedAt: new Date('2024-02-15'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Énergie et de l\'Eau',
      contactEmail: 'contact@energie.gov.ml',
      granularity: 'Installation',
    },
    quality: {
      overall: 85,
      completeness: 85,
      accuracy: 85,
      documentation: 85,
      metadata: 88,
      formats: 85,
      updates: 82,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-13',
    title: 'Statistiques du Tourisme - Arrivées et recettes (2020-2024)',
    description: 'Données touristiques du Mali : nombre de touristes par nationalité, durée moyenne de séjour, recettes touristiques, principaux sites visités. Données mensuelles et annuelles.',
    organization: organizations[0],
    theme: themes[0],
    keywords: ['tourisme', 'voyageurs', 'recettes', 'arrivées', 'sites touristiques', 'nationalité'],
    formats: ['CSV', 'Excel'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-05-05'),
    updateFrequency: 'Trimestriel',
    downloads: 2890,
    views: 12300,
    rating: 4.0,
    ratingCount: 32,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-03-31') },
    files: [
      {
        id: 'file-13',
        name: 'tourisme_2020_2024.csv',
        format: 'CSV',
        size: 780000,
        url: '/data/ds-13/tourisme_2020_2024.csv',
        checksum: 'fgh567ghi678',
        rows: 3456,
        columns: 12,
        addedAt: new Date('2024-05-05'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Économie et des Finances',
      contactEmail: 'contact@mef.gov.ml',
      granularity: 'Nationalité',
    },
    quality: {
      overall: 82,
      completeness: 85,
      accuracy: 80,
      documentation: 80,
      metadata: 85,
      formats: 82,
      updates: 80,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-14',
    title: 'Infrastructures hydrauliques - Puits, forages et bornes-fontaines',
    description: 'Inventaire national des points d\'eau potable : puits, forages, bornes-fontaines, mini-AEP. Localisation géographique, débits, état fonctionnel et gestionnaire.',
    organization: organizations[13],
    theme: themes[3],
    keywords: ['eau', 'hydraulique', 'puits', 'forages', 'bornes-fontaines', 'AEP', 'eau potable'],
    formats: ['GeoJSON', 'Shapefile', 'CSV'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
    updateFrequency: 'Annuel',
    downloads: 6789,
    views: 28900,
    rating: 4.5,
    ratingCount: 76,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-14',
        name: 'points_eau_2024.geojson',
        format: 'GeoJSON',
        size: 23400000,
        url: '/data/ds-14/points_eau_2024.geojson',
        checksum: 'ghi678hij789',
        rows: 34567,
        columns: 16,
        addedAt: new Date('2024-03-20'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Énergie et de l\'Eau',
      contactEmail: 'contact@energie.gov.ml',
      granularity: 'Point d\'eau',
    },
    quality: {
      overall: 90,
      completeness: 92,
      accuracy: 88,
      documentation: 88,
      metadata: 90,
      formats: 92,
      updates: 88,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-15',
    title: 'Taux de scolarisation par région et par sexe (2020-2024)',
    description: 'Taux de scolarisation brut et net par niveau d\'enseignement, région et sexe. Évolution sur 5 ans avec indicateurs de parité filles-garçons.',
    organization: organizations[2],
    theme: themes[2],
    keywords: ['éducation', 'scolarisation', 'taux', 'région', 'sexe', 'parité', 'filles', 'garçons'],
    formats: ['CSV', 'Excel', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-15'),
    updateFrequency: 'Annuel',
    downloads: 4567,
    views: 20100,
    rating: 4.3,
    ratingCount: 54,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-06-30') },
    files: [
      {
        id: 'file-15',
        name: 'taux_scolarisation_2020_2024.csv',
        format: 'CSV',
        size: 980000,
        url: '/data/ds-15/taux_scolarisation_2020_2024.csv',
        checksum: 'hij789ijk890',
        rows: 2592,
        columns: 12,
        addedAt: new Date('2024-06-15'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Éducation Nationale',
      contactEmail: 'contact@education.gov.ml',
      granularity: 'Région',
    },
    quality: {
      overall: 88,
      completeness: 88,
      accuracy: 88,
      documentation: 88,
      metadata: 90,
      formats: 88,
      updates: 88,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-16',
    title: 'Recettes fiscales par catégorie d\'impôts (2020-2024)',
    description: 'Recouvrement des impôts directs et indirects par catégorie : IR, IS, TVA, droits de douane, impôts locaux. Données trimestrielles et comparaisons avec les prévisions budgétaires.',
    organization: organizations[10],
    theme: themes[7],
    keywords: ['fiscalité', 'impôts', 'recettes', 'IR', 'IS', 'TVA', 'droits de douane', 'budget'],
    formats: ['CSV', 'Excel'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-20'),
    updateFrequency: 'Trimestriel',
    downloads: 3890,
    views: 15600,
    rating: 4.2,
    ratingCount: 41,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-03-31') },
    files: [
      {
        id: 'file-16',
        name: 'recettes_fiscales_2020_2024.csv',
        format: 'CSV',
        size: 670000,
        url: '/data/ds-16/recettes_fiscales_2020_2024.csv',
        checksum: 'ijk890jkl901',
        rows: 720,
        columns: 10,
        addedAt: new Date('2024-04-20'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Direction Générale des Impôts',
      contactEmail: 'contact@impots.gov.ml',
      granularity: 'Catégorie d\'impôt',
    },
    quality: {
      overall: 90,
      completeness: 92,
      accuracy: 90,
      documentation: 88,
      metadata: 90,
      formats: 90,
      updates: 90,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-17',
    title: 'Couverture réseau mobile et Internet par région',
    description: 'Cartographie de la couverture des réseaux mobiles (2G, 3G, 4G) et d\'Internet fixe par région et localité. Données sur les opérateurs, les sites et les débits.',
    organization: organizations[11],
    theme: themes[4],
    keywords: ['télécommunications', 'mobile', 'Internet', 'couverture', 'réseau', 'opérateurs', '4G'],
    formats: ['GeoJSON', 'Shapefile', 'CSV', 'PDF'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-05-15'),
    updateFrequency: 'Semestriel',
    downloads: 5678,
    views: 24500,
    rating: 4.4,
    ratingCount: 68,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-01-01'), end: new Date('2024-12-31') },
    files: [
      {
        id: 'file-17',
        name: 'couverture_mobile_2024.geojson',
        format: 'GeoJSON',
        size: 45600000,
        url: '/data/ds-17/couverture_mobile_2024.geojson',
        checksum: 'jkl901klm012',
        rows: 45678,
        columns: 14,
        addedAt: new Date('2024-01-30'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Autorité de Régulation des Télécommunications',
      contactEmail: 'contact@artp.ml',
      granularity: 'Localité',
    },
    quality: {
      overall: 92,
      completeness: 90,
      accuracy: 92,
      documentation: 92,
      metadata: 95,
      formats: 92,
      updates: 92,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-18',
    title: 'Production d\'électricité et consommation par secteur',
    description: 'Statistiques de production et consommation d\'électricité du Mali : sources de production (thermique, hydroélectrique, solaire), consommation par secteur (résidentiel, industriel, commercial).',
    organization: organizations[13],
    theme: themes[3],
    keywords: ['électricité', 'énergie', 'production', 'consommation', 'secteur', 'thermique', 'hydroélectrique'],
    formats: ['CSV', 'Excel', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-04-25'),
    updatedAt: new Date('2024-04-25'),
    updateFrequency: 'Mensuel',
    downloads: 3456,
    views: 14200,
    rating: 4.1,
    ratingCount: 36,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-03-31') },
    files: [
      {
        id: 'file-18',
        name: 'electricite_2020_2024.csv',
        format: 'CSV',
        size: 1230000,
        url: '/data/ds-18/electricite_2020_2024.csv',
        checksum: 'klm012lmn123',
        rows: 2520,
        columns: 10,
        addedAt: new Date('2024-04-25'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Énergie et de l\'Eau',
      contactEmail: 'contact@energie.gov.ml',
      granularity: 'Mensuel',
    },
    quality: {
      overall: 88,
      completeness: 90,
      accuracy: 85,
      documentation: 85,
      metadata: 88,
      formats: 90,
      updates: 88,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-19',
    title: 'Élections législatives 2024 - Résultats par circonscription',
    description: 'Résultats officiels des élections législatives 2024 : nombre de voix et pourcentages par parti politique et circonscription électorale. Taux de participation par circonscription.',
    organization: organizations[14],
    theme: themes[6],
    keywords: ['élections', 'législatives', 'résultats', 'partis politiques', 'circonscription', 'participation'],
    formats: ['CSV', 'Excel', 'PDF', 'JSON'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
    updateFrequency: 'Ponctuel',
    downloads: 7890,
    views: 45600,
    rating: 4.6,
    ratingCount: 112,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2024-03-24'), end: new Date('2024-03-24') },
    files: [
      {
        id: 'file-19',
        name: 'elections_legislatives_2024.csv',
        format: 'CSV',
        size: 1560000,
        url: '/data/ds-19/elections_legislatives_2024.csv',
        checksum: 'lmn123mno234',
        rows: 5580,
        columns: 14,
        addedAt: new Date('2024-04-05'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Commission Électorale Nationale Indépendante',
      contactEmail: 'contact@ceni.ml',
      granularity: 'Circonscription',
    },
    quality: {
      overall: 95,
      completeness: 98,
      accuracy: 95,
      documentation: 95,
      metadata: 95,
      formats: 95,
      updates: 90,
    },
    status: 'published',
    featured: false,
  },
  {
    id: 'ds-20',
    title: 'Résultats scolaires - BEPC et BAC par région (2020-2024)',
    description: 'Statistiques des examens du BEPC et du Baccalauréat : taux de réussite par région, par série et par sexe. Effectifs des candidats et des admis.',
    organization: organizations[2],
    theme: themes[2],
    keywords: ['éducation', 'examens', 'BEPC', 'BAC', 'résultats', 'taux de réussite', 'région'],
    formats: ['CSV', 'Excel'],
    license: 'CC-BY-4.0',
    publishedAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-10'),
    updateFrequency: 'Annuel',
    downloads: 6543,
    views: 28900,
    rating: 4.4,
    ratingCount: 73,
    spatialCoverage: 'National',
    temporalCoverage: { start: new Date('2020-01-01'), end: new Date('2024-06-30') },
    files: [
      {
        id: 'file-20',
        name: 'resultats_examens_2020_2024.csv',
        format: 'CSV',
        size: 1340000,
        url: '/data/ds-20/resultats_examens_2020_2024.csv',
        checksum: 'mno234nop345',
        rows: 4320,
        columns: 12,
        addedAt: new Date('2024-06-10'),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: 'Ministère de l\'Éducation Nationale',
      contactEmail: 'contact@education.gov.ml',
      granularity: 'Région',
    },
    quality: {
      overall: 92,
      completeness: 92,
      accuracy: 90,
      documentation: 90,
      metadata: 92,
      formats: 92,
      updates: 92,
    },
    status: 'published',
    featured: false,
  },
  // Continue with more datasets... (I'll add more to reach 50+)
];

// Generate additional datasets programmatically to reach 50+
const additionalDatasets: Dataset[] = Array.from({ length: 30 }, (_, i) => {
  const index = i + 21;
  const themeIndex = Math.floor(Math.random() * themes.length);
  const orgIndex = Math.floor(Math.random() * organizations.length);

  return {
    id: `ds-${index}`,
    title: `Données supplémentaires ${index} - ${themes[themeIndex].name}`,
    description: `Jeu de données complémentaire pour le domaine ${themes[themeIndex].name}. Contient des statistiques détaillées et des analyses sur divers aspects thématiques.`,
    organization: organizations[orgIndex],
    theme: themes[themeIndex],
    keywords: [themes[themeIndex].name.toLowerCase(), 'statistiques', 'données', 'analyse'],
    formats: ['CSV', 'Excel', 'JSON'].slice(0, Math.floor(Math.random() * 3) + 1) as any,
    license: ['CC-BY-4.0', 'CC-BY-SA-4.0', 'CC-Zero', 'ODbL'][Math.floor(Math.random() * 4)] as any,
    publishedAt: new Date(2024, Math.floor(Math.random() * 7), Math.floor(Math.random() * 28) + 1),
    updatedAt: new Date(2024, Math.floor(Math.random() * 7), Math.floor(Math.random() * 28) + 1),
    updateFrequency: ['Ponctuel', 'Annuel', 'Mensuel', 'Trimestriel'][Math.floor(Math.random() * 4)] as any,
    downloads: Math.floor(Math.random() * 10000) + 1000,
    views: Math.floor(Math.random() * 50000) + 5000,
    rating: Math.round((Math.random() * 2 + 3) * 10) / 10,
    ratingCount: Math.floor(Math.random() * 200) + 20,
    spatialCoverage: ['National', 'Régional', 'Local'][Math.floor(Math.random() * 3)],
    temporalCoverage: {
      start: new Date(2020, 0, 1),
      end: new Date(2024, 6, 30),
    },
    files: [
      {
        id: `file-${index}`,
        name: `dataset_${index}.csv`,
        format: 'CSV',
        size: Math.floor(Math.random() * 5000000) + 500000,
        url: `/data/ds-${index}/dataset_${index}.csv`,
        checksum: `hash${index}`,
        rows: Math.floor(Math.random() * 20000) + 1000,
        columns: Math.floor(Math.random() * 15) + 5,
        addedAt: new Date(2024, Math.floor(Math.random() * 7), Math.floor(Math.random() * 28) + 1),
        isPrimary: true,
      },
    ],
    metadata: {
      language: 'fr',
      publisher: organizations[orgIndex].name,
      contactEmail: organizations[orgIndex].email || 'contact@example.com',
      granularity: 'Donnée',
    },
    quality: {
      overall: Math.floor(Math.random() * 20) + 80,
      completeness: Math.floor(Math.random() * 20) + 80,
      accuracy: Math.floor(Math.random() * 20) + 80,
      documentation: Math.floor(Math.random() * 20) + 80,
      metadata: Math.floor(Math.random() * 20) + 80,
      formats: Math.floor(Math.random() * 20) + 80,
      updates: Math.floor(Math.random() * 20) + 80,
    },
    status: 'published',
    featured: Math.random() > 0.8,
  };
});

// Merge all datasets
export const allDatasets: Dataset[] = [...datasets, ...additionalDatasets];

// Stats
export const globalStats: Stats = {
  totalDatasets: allDatasets.length,
  totalOrganizations: organizations.length,
  totalUsers: 2876,
  totalDownloads: 456789,
  totalViews: 1234567,
  newDatasetsThisMonth: 15,
  newUsersThisMonth: 234,
  downloadsThisMonth: 45678,
  activeUsers: 1234,
};

// Users
export const users: User[] = [
  {
    id: 'user-1',
    name: 'Admin Principal',
    email: 'admin@jdom.ml',
    role: 'admin',
    type: 'organization',
    avatar: '/avatars/admin.jpg',
    createdAt: new Date('2020-01-01'),
    status: 'active',
    favorites: ['ds-1', 'ds-4', 'ds-6'],
    downloads: 456,
  },
  {
    id: 'user-2',
    name: 'Producteur INSTAT',
    email: 'instat@producer.gov.ml',
    role: 'producer',
    type: 'organization',
    organizationId: 'org-4',
    avatar: '/avatars/instat.jpg',
    createdAt: new Date('2020-03-01'),
    status: 'active',
    favorites: [],
    downloads: 234,
  },
  {
    id: 'user-3',
    name: 'Citoyen Alpha',
    email: 'citoyen@example.com',
    role: 'citizen',
    type: 'citizen',
    avatar: '/avatars/citoyen1.jpg',
    createdAt: new Date('2023-06-15'),
    status: 'active',
    favorites: ['ds-1', 'ds-2', 'ds-3', 'ds-4'],
    downloads: 123,
  },
];

// Comments
export const comments: Comment[] = [
  {
    id: 'comment-1',
    datasetId: 'ds-1',
    userId: 'user-3',
    userName: 'Citoyen Alpha',
    userAvatar: '/avatars/citoyen1.jpg',
    content: 'Très utile pour notre recherche sur l\'éducation au Mali. Merci pour ces données complètes !',
    createdAt: new Date('2024-06-15'),
    likes: 23,
  },
  {
    id: 'comment-2',
    datasetId: 'ds-4',
    userId: 'user-3',
    userName: 'Citoyen Alpha',
    userAvatar: '/avatars/citoyen1.jpg',
    content: 'Est-ce que les données sont mises à jour chaque trimestre ? Excellent travail.',
    createdAt: new Date('2024-06-10'),
    likes: 15,
  },
];

// Reviews
export const reviews: Review[] = [
  {
    id: 'review-1',
    datasetId: 'ds-1',
    userId: 'user-3',
    userName: 'Citoyen Alpha',
    rating: 5,
    title: 'Données complètes et bien documentées',
    content: 'Excellent jeu de données pour tous ceux qui travaillent sur l\'éducation au Mali. Les métadonnées sont claires et les données fiables.',
    createdAt: new Date('2024-06-15'),
    helpful: 45,
  },
  {
    id: 'review-2',
    datasetId: 'ds-4',
    userId: 'user-3',
    userName: 'Citoyen Alpha',
    rating: 4,
    title: 'Très bon suivi économique',
    content: 'Données économiques fiables et bien mises à jour. Serait idéal d\'avoir plus de détails régionaux.',
    createdAt: new Date('2024-06-10'),
    helpful: 32,
  },
];

// Activities
export const activities: Activity[] = [
  {
    id: 'activity-1',
    type: 'dataset_published',
    userId: 'user-2',
    userName: 'Producteur INSTAT',
    description: 'a publié le dataset "Indicateurs économiques trimestriels"',
    datasetId: 'ds-4',
    datasetTitle: 'Indicateurs économiques trimestriels (2020-2024)',
    timestamp: new Date('2024-04-15T10:30:00'),
  },
  {
    id: 'activity-2',
    type: 'dataset_downloaded',
    datasetId: 'ds-1',
    datasetTitle: 'Établissements scolaires du Mali (2024)',
    description: 'téléchargement du dataset',
    timestamp: new Date('2024-06-20T14:25:00'),
  },
  {
    id: 'activity-3',
    type: 'comment_posted',
    userId: 'user-3',
    userName: 'Citoyen Alpha',
    datasetId: 'ds-1',
    datasetTitle: 'Établissements scolaires du Mali (2024)',
    description: 'a posté un commentaire',
    timestamp: new Date('2024-06-15T09:15:00'),
  },
  {
    id: 'activity-4',
    type: 'user_registered',
    userId: 'user-3',
    userName: 'Citoyen Alpha',
    description: 'nouvel utilisateur inscrit',
    timestamp: new Date('2023-06-15T16:45:00'),
  },
];

// Use Cases
export const useCases: UseCase[] = [
  {
    id: 'usecase-1',
    title: 'Observatoire de l\'Éducation du Mali',
    description: 'Plateforme de visualisation interactive des données éducatives utilisant les données de l\'INSTAT et du Ministère de l\'Éducation.',
    datasets: [datasets[0], datasets[9], datasets[14]],
    organization: 'Université de Bamako',
    website: 'https://observatoire-education-uni-bamako.ml',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'usecase-2',
    title: 'Carte Santé Mali',
    description: 'Application mobile permettant de localiser les centres de santé et d\'accéder aux informations sur leurs capacités et disponibilités.',
    datasets: [datasets[1]],
    organization: 'ONG Santé pour Tous',
    website: 'https://cartesante-ong.ml',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'usecase-3',
    title: 'Tableau de bord Économie',
    description: 'Dashboard interactif pour le suivi des indicateurs économiques du Mali, utilisé par les chercheurs et décideurs.',
    datasets: [datasets[3], datasets[6]],
    organization: 'Think Tank Économique',
    website: 'https://economie-dashboard.ml',
    createdAt: new Date('2024-02-15'),
  },
];
